version: "3.9"

services:
  autorizador:
    build: ./autorizador
    container_name: servicio_autorizador
    volumes:
      - ./event_log.txt:/app/event_log.txt
    ports:
      - "5001:5000"
    environment:
      - JWT_SECRET_KEY=mi_clave_secreta_ultra_segura_2025
    networks:
      - app_network

  logistica:
    build: ./logistica
    container_name: servicio_logistica
    volumes:
      - ./event_log.txt:/app/event_log.txt
    ports:
      - "5002:5000"
    environment:
      - JWT_SECRET_KEY=mi_clave_secreta_ultra_segura_2025
    depends_on:
      - autorizador
    networks:
      - app_network

  clientes:
    build: ./clientes
    container_name: servicio_clientes
    volumes:
      - ./event_log.txt:/app/event_log.txt
    ports:
      - "5003:5000"
    environment:
      - AUTH_URL=http://servicio_autorizador:5000/login
      - LOGISTICS_URL=http://servicio_logistica:5000/routes
    depends_on:
      - autorizador
      - logistica
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
